services:
  serving:
    image: tensorflow/serving
    container_name: serving
    env_file:
      - .env
    volumes:
      - "./saved_models/${MODEL_NAME}:/models/${MODEL_NAME}"
    expose:
      - 8501

  processing:
    image: alzh-processing
    container_name: processing
    volumes:
      - "./data:/app/data"
      - "./logs:/app/logs"
    env_file:
      - .env
    depends_on:
      - serving
    expose:
      - 5000

  webapp:
    build: webapp
    image: alzh-webapp
    container_name: webapp
    volumes:
      - ./webapp/logs:/app/logs
    env_file:
      - .env
    depends_on:
      - processing
    ports:
      - "8080:8080"
    entrypoint: ["python", "./app.py"]
